### ISSUE TITLE
We couldn't send an email there

### ISSUE THREAD

**Issue by Naamloos** [duolicious/duolicious-backend#284]
It seems I can no longer log in. Not sure whether servers are down?

I get the error noted in the issue title. I'm using an outlook.com mail.

**Comment by SilvoSwordo** [comment]
Similar issue, but there is no error indicated.
I have laposte.net mail address and an _active_ account dating from november. But after being disconnected following some servers hiccups, I can't connect again because the backend does not actually send me any mail. I however do not get an error, the website acts as if the mail was correctly sent.
I note that I received mail notification of DMs until may 6th, after which I stopped receiving ant mails from Duolicious even after receiving DMs.

**Comment by Naamloos** [comment]
For me, it seems resolved for the time being, but it may be worth checking into so I'll keep this issue open for the time being.

**Comment by SilvoSwordo** [comment]
No, go ahead and close it, since the problem seems to be different I'll open an issue that's more descriptive of what happened to me.

**Comment by Naamloos** [comment]
¯\\\_(ツ)\_/¯

**Comment by nonetrix** [comment]
Going to inspect element says 403 forbidden for me, using a different IP on a different email works but not my email I used. I think I was falsely banned somehow
