### ISSUE TITLE
Ban tags that might be used by pedos

### ISSUE THREAD

**Issue by nonetrix** [duolicious/duolicious-backend#285]
![1000098800](https://github.com/duolicious/duolicious-backend/assets/45698918/16bfb0f9-7c71-4a36-9715-b81298f63120)
Wtf

**Comment by nonetrix** [comment]
Probably want to ban the users using these tags as well

**Comment by duogenesis** [comment]
They've all been banned. Thanks for the report.

**Comment by nonetrix** [comment]
Thanks, probably would be ideal to implement a block list just to ban these from being used. Really hope this doesn't become a common accordance, but moderation would be quite hard I imagine and ideally shouldn't extend past anything that's illegal in my opinion

**Comment by duogenesis** [comment]
Related: https://github.com/duolicious/duolicious-backend/pull/334, https://github.com/duolicious/duolicious-backend/pull/336, https://github.com/duolicious/duolicious-backend/pull/338, https://github.com/duolicious/duolicious-backend/pull/339, https://github.com/duolicious/duolicious-backend/pull/340, https://github.com/duolicious/duolicious-backend/pull/342, https://github.com/duolicious/duolicious-backend/pull/344, https://github.com/duolicious/duolicious-backend/pull/345, https://github.com/duolicious/duolicious-backend/pull/346, https://github.com/duolicious/duolicious-backend/pull/349, https://github.com/duolicious/duolicious-backend/pull/350, https://github.com/duolicious/duolicious-backend/pull/351, https://github.com/duolicious/duolicious-backend/pull/360, https://github.com/duolicious/duolicious-backend/pull/371, https://github.com/duolicious/duolicious-backend/pull/375, https://github.com/duolicious/duolicious-backend/pull/379, https://github.com/duolicious/duolicious-backend/pull/380, https://github.com/duolicious/duolicious-backend/pull/381, https://github.com/duolicious/duolicious-backend/pull/382, https://github.com/duolicious/duolicious-backend/pull/390

**Comment by nonetrix** [comment]
>slurs in there too

Oh so that's why I was banned......... I only included a anti semitic slur in my bio as a joke because I'm Jewish in real life and thought it would be funny
![GOrh0f9XEAA_gRo](https://github.com/duolicious/duolicious-backend/assets/45698918/910546bc-d9f6-4cf4-8bb6-51efcb6efb85)

I can explain (I cannot)

**Comment by duogenesis** [comment]
@nonetrix Only the clubs themselves were banned as a result of the PRs in https://github.com/duolicious/duolicious-backend/issues/285#issuecomment-2198656150. If you were banned after those PRs were merged, it was probably for a different reason.

> I only included a anti semitic slur in my bio as a joke because I'm Jewish in real life and thought it would be funny. I'm not racist though

I hear you, but there's not much I can do. Duolicious requires moderation of that stuff because Google Play requires it, and (I assume) Google requires it because governments require it.

At the risk of ranting about a topic I'm ignorant on, I think that the moderation policies which online platforms are required to adopt to protect the protected classes probably (and sadly) [have](https://en.wikipedia.org/wiki/Ironic_process_theory) the [opposite](https://en.wikipedia.org/wiki/Reactance_(psychology)) of [the](https://en.wikipedia.org/wiki/Self-fulfilling_prophecy) intended [effect](https://en.wikipedia.org/wiki/Streisand_effect).
